# SPDX-License-Identifier: Apache-2.0

# board specific
CONFIG_FURRYDEX_DISPLAY_WIDTH=132
CONFIG_FURRYDEX_DISPLAY_HEIGHT=250

# not 4125 due to weird 132-pixel width
CONFIG_FURRYDEX_FRAME_BYTES_BUFFER=4250
# the LCD expects 4125 bits. this is fuckin weird. fix it later.
CONFIG_FURRYDEX_FRAME_BYTES_DISPLAY=4125
CONFIG_FURRYDEX_CURSOR_START_X=0
CONFIG_FURRYDEX_CURSOR_START_Y=249
CONFIG_BATTERY_USE_REG_LDO_MAPPING=y
CONFIG_LUA_HEAP_SIZE=262144

CONFIG_DK_LIBRARY=y